version: '3'

networks:
  project:
    name: project

services:

    nginx:
      image: nginx:${NGINX_VERSION}
      container_name: nginx
      restart: always
      networks:
        - project
      ports: 
        - "${NGINX_PORT}:80"
        - "${NGINX_SSL_PORT}:443"
      volumes:
        - "./src:/var/www/html"
      depends_on:
        - php
        - redis
        - mysql

    php:
      image: php:${PHP_VERSION}-fpm-alpine
      container_name: php-fpm
      restart: always
      networks:
        - project
      volumes:
        - "./src:/var/www/html"

    composer:
      image: "composer"
      container_name: composer
      networks:
        - project
      command: install
      volumes:
        - "./src:/var/www/html"
      depends_on:
        - php
     

    mysql:
      image: mysql:${MYSQL_VERSION}
      platform: linux/x86_64
      container_name: mysql
      restart: always
      ports: 
       - "${MYSQL_PORT}:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
      networks:
        - project


    redis:
      image: redis:latest
      container_name: redis
      restart: unless-stopped
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - project